### ISSUE TITLE
Implementation of Facebook login button

### ISSUE THREAD

**Issue by osain-az** [Ringrev/facebook-api-rs#15]
### Overview of feature 📝
This  task is a following up from the  task Card "Should we use the official facebook logoin button with logo ". 
Since the result of the task was to design our own button using the  guide, in this card  the design will be implemented. 

### Which problem is the feature or enhancement solving❓
Facebook login button design.

### Documentation & Help ℹ️

**Comment by Beateringrev** [comment]
Yes, design 1 is the way to go :) And in Norwegian it should say "Logg inn med Facebook" (fyi @osain-az )

**Comment by osain-az** [comment]
facebook provide  different "f logo" which can be downloaded as a zip file, for some reason  the zip file i downloaded from facebook does not include the  "f  logo" shown in design  1. for now  design 2 is used on the example page, although switching to design 1 is just changing  the logo and colour @Beateringrev   @arn-the-long-beard
