### ISSUE TITLE
Instagram posting Tips

### ISSUE THREAD

**Issue by arn-the-long-beard** [Ringrev/facebook-api-rs#27]
### Overview of feature 📝

From the review of the posting platform, the insta posting should have both "description" and "first comment" when posting ("firs comment" is where the hashtags of the comment go)
### Which problem is the feature or enhancement solving❓
This separates the  description  from the hastag  to give a nice view 

### Documentation & Help ℹ️

**Comment by osain-az** [comment]
The adding of the hashtag as comment when posting should be handle by the developer.
The developer could chain the post_comment method to post the hashtag as comment. This should be done when the developer has ensured that the media container is ready before posting. 
To check if the media container is ready  the  "status method" in the media endpoint  should be used and if the  response is "FINISHED" then the media is ready. 

If posting hashtag in he comment is not important then the hashtag should be in the same input  with the "caption".
@arn-the-long-beard

**Comment by arn-the-long-beard** [comment]
@osain-az  you can put this task as done if there is nothing more to do on it.
